apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "http://<your-argocd-server>:8080"  # Replace with your ArgoCD server URL

  service.email: |
    username: $email-username
    password: $email-password
    host: smtp.gmail.com
    port: 465
    from: $email-username

  context.argocdUrl: "http://3.255.96.246:8080"

  # Template for Degraded health
  template.email-health-degraded: |
    email:
      subject: "[ArgoCD] {{.app.metadata.name}} health is {{.app.status.health.status}}"
    message: |
      🚨 Application: {{.app.metadata.name}}
      📂 Namespace: {{.app.metadata.namespace}}
      🔄 Sync status: {{.app.status.sync.status}}
      📌 Revision: {{.app.status.sync.revision}}
      ❤️ Health status: {{.app.status.health.status}}
      📝 Health message: {{.app.status.health.message}}
      ⚙️ Last operation: {{ if .app.operationState }}{{ .app.operationState.phase }}{{ else }}<none>{{ end }}
      🔗 Details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  # Template for Deployed (synced + healthy)
  template.email-deployed: |
    email:
      subject: "[ArgoCD] {{.app.metadata.name}} successfully deployed 🎉"
    message: |
      ✅ Application: {{.app.metadata.name}}
      📂 Namespace: {{.app.metadata.namespace}}
      🔄 Sync status: {{.app.status.sync.status}}
      📌 Revision: {{.app.status.sync.revision}}
      ❤️ Health status: {{.app.status.health.status}}
      ⚙️ Last operation: {{ if .app.operationState }}{{ .app.operationState.phase }}{{ else }}<none>{{ end }}
      Finished at: {{ if .app.operationState }}{{ .app.operationState.finishedAt }}{{ end }}
      🔗 Details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  # Triggers
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      oncePer: app.status.sync.revision
      send: [email-health-degraded]

  trigger.on-deployed: |
    - when: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
      send: [email-deployed]
