# chai-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chai-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.email: "<receiver@example.com>" # receiver email address, The `.email` notifier is defined in argocd-notifications-cm.yaml - service.email , you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>
    notifications.argoproj.io/subscribe.on-deployed.email: "<receiver@example.com>" # receiver email address, you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/argocd-demos.git
    targetRevision: main
    path: applicationsets/chai-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true