apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups, email]'

  policy.csv: |
    # Define admin/operator permissions
    p, role:repo-admin, applications, create, */*, allow
    p, role:repo-admin, applications, get,    */*, allow
    p, role:repo-admin, applications, update, */*, allow
    p, role:repo-admin, applications, sync,   */*, allow
    p, role:repo-admin, applications, delete, */*, allow
    p, role:repo-admin, repositories, create, */*, allow
    p, role:repo-admin, repositories, *, */*, allow
    p, role:repo-admin, projects, *, *, allow

    # Bind by email (fallback)
    g, <your-github-email>, role:repo-admin
    g, amitabhdevops2024@gmail.com, role:repo-admin

    # Keep org binding for when it works
    g, <your-github-org>:members, role:repo-admin
    # g, tws-argocd:members, role:repo-admin

  policy.default: role:readonly