apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # dex.github.clientId: <your-client-id>
  # dex.github.clientSecret: <your-client-secret>
  dex.github.clientId: Ov23li9A59r0PZFDOJZi
  dex.github.clientSecret: ae87261660825b2bf630b7267b9d66e5535c099d