apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # url: https://<your-argocd-url>:8080
  url: https://54.78.142.99:8080
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex.github.clientId
        clientSecret: $dex.github.clientSecret
        redirectURI: https://<your-argocd-url>/api/dex/callback
        # If you want to restrict login to specific GitHub organizations, uncomment and modify:
        # orgs:
        # - name: my-github-org